// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameManifest(arg1) {
  return window['go']['system']['AssetHandler']['GetGameManifest'](arg1);
}

export function ListInstalledAssets() {
  return window['go']['system']['AssetHandler']['ListInstalledAssets']();
}
