// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';

export function GetGameManifest(arg1:string):Promise<system.GameManifest>;

export function ListInstalledAssets():Promise<Array<system.InstalledAsset>>;
