// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {model} from '../models';

export function CreateCommentator(arg1:dto.CreateCommentatorRequest):Promise<model.Commentator>;

export function DeleteCommentator(arg1:string):Promise<void>;

export function GetAll():Promise<Array<model.Commentator>>;
