// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCommentator(arg1) {
  return window['go']['system']['CommentatorHandler']['CreateCommentator'](arg1);
}

export function DeleteCommentator(arg1) {
  return window['go']['system']['CommentatorHandler']['DeleteCommentator'](arg1);
}

export function GetAll() {
  return window['go']['system']['CommentatorHandler']['GetAll']();
}
