// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {model} from '../models';

export function CreateEvent(arg1:dto.CreateEventRequest):Promise<void>;

export function GetAllEvents():Promise<Array<model.Event>>;
