// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvent(arg1) {
  return window['go']['system']['EventHandler']['CreateEvent'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['system']['EventHandler']['DeleteEvent'](arg1);
}

export function GetAllEvents() {
  return window['go']['system']['EventHandler']['GetAllEvents']();
}
