// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePlayer(arg1) {
  return window['go']['system']['PlayerHandler']['CreatePlayer'](arg1);
}

export function DeletePlayer(arg1) {
  return window['go']['system']['PlayerHandler']['DeletePlayer'](arg1);
}

export function GetAll() {
  return window['go']['system']['PlayerHandler']['GetAll']();
}
