// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {model} from '../models';

export function CreatePlayer(arg1:dto.CreatePlayerRequest):Promise<model.Player>;

export function DeletePlayer(arg1:string):Promise<void>;

export function GetAll():Promise<Array<model.Player>>;

export function GetAllStats():Promise<Array<dto.PlayerStats>>;
