// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Update(arg1) {
  return window['go']['system']['ScoreboardHandler']['Update'](arg1);
}
