// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function IsRunning():Promise<boolean>;

export function PushUpdate(arg1:dto.MatchDataUpdateDTO):Promise<void>;

export function StartServer(arg1:number):Promise<void>;

export function StopServer():Promise<void>;
