// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsRunning() {
  return window['go']['system']['ServerHandler']['IsRunning']();
}

export function PushUpdate(arg1) {
  return window['go']['system']['ServerHandler']['PushUpdate'](arg1);
}

export function StartServer(arg1) {
  return window['go']['system']['ServerHandler']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['system']['ServerHandler']['StopServer']();
}
