// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {model} from '../models';

export function CreateSet(arg1:dto.CreateSetRequest):Promise<model.Set>;

export function DeleteSet(arg1:string):Promise<void>;

export function GetByTournament(arg1:string):Promise<Array<model.Set>>;

export function ReportResult(arg1:dto.ReportSetRequest):Promise<void>;

export function UpdateScore(arg1:dto.UpdateSetScoreRequest):Promise<void>;
