// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSet(arg1) {
  return window['go']['system']['SetHandler']['CreateSet'](arg1);
}

export function DeleteSet(arg1) {
  return window['go']['system']['SetHandler']['DeleteSet'](arg1);
}

export function GetByTournament(arg1) {
  return window['go']['system']['SetHandler']['GetByTournament'](arg1);
}

export function ReportResult(arg1) {
  return window['go']['system']['SetHandler']['ReportResult'](arg1);
}

export function UpdateScore(arg1) {
  return window['go']['system']['SetHandler']['UpdateScore'](arg1);
}
