// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportTournament(arg1, arg2) {
  return window['go']['system']['StartGGHandler']['ImportTournament'](arg1, arg2);
}
