// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';

export function GetActivePack():Promise<string>;

export function GetActiveTemplate(arg1:string):Promise<string>;

export function GetOverlayManifest(arg1:string):Promise<system.OverlayManifest>;

export function ListPacks():Promise<Array<system.PackInfo>>;

export function SetActivePack(arg1:string):Promise<void>;

export function SetActiveTemplate(arg1:string,arg2:string):Promise<void>;
