// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActivePack() {
  return window['go']['system']['TemplateHandler']['GetActivePack']();
}

export function GetActiveTemplate(arg1) {
  return window['go']['system']['TemplateHandler']['GetActiveTemplate'](arg1);
}

export function GetOverlayManifest(arg1) {
  return window['go']['system']['TemplateHandler']['GetOverlayManifest'](arg1);
}

export function ListPacks() {
  return window['go']['system']['TemplateHandler']['ListPacks']();
}

export function SetActivePack(arg1) {
  return window['go']['system']['TemplateHandler']['SetActivePack'](arg1);
}

export function SetActiveTemplate(arg1, arg2) {
  return window['go']['system']['TemplateHandler']['SetActiveTemplate'](arg1, arg2);
}
