// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateTournament(arg1) {
  return window['go']['system']['TournamentHandler']['ActivateTournament'](arg1);
}

export function CreateTournament(arg1) {
  return window['go']['system']['TournamentHandler']['CreateTournament'](arg1);
}

export function DeleteTournament(arg1) {
  return window['go']['system']['TournamentHandler']['DeleteTournament'](arg1);
}

export function GetAll() {
  return window['go']['system']['TournamentHandler']['GetAll']();
}

export function GetByEvent(arg1) {
  return window['go']['system']['TournamentHandler']['GetByEvent'](arg1);
}

export function UpdateTournament(arg1) {
  return window['go']['system']['TournamentHandler']['UpdateTournament'](arg1);
}
