// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {model} from '../models';

export function ActivateTournament(arg1:string):Promise<void>;

export function CreateTournament(arg1:dto.CreateTournamentRequest):Promise<model.Tournament>;

export function DeleteTournament(arg1:string):Promise<void>;

export function GetAll():Promise<Array<model.Tournament>>;

export function GetByEvent(arg1:string):Promise<Array<model.Tournament>>;

export function UpdateTournament(arg1:dto.UpdateTournamentRequest):Promise<void>;
