// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CreateCommentatorRequest {
    "name": string;
    "handle": string;
    "pronouns": string;

    /** Creates a new CreateCommentatorRequest instance. */
    constructor($$source: Partial<CreateCommentatorRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("handle" in $$source)) {
            this["handle"] = "";
        }
        if (!("pronouns" in $$source)) {
            this["pronouns"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateCommentatorRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateCommentatorRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateCommentatorRequest($$parsedSource as Partial<CreateCommentatorRequest>);
    }
}

export class CreateEventRequest {
    "name": string;

    /** Creates a new CreateEventRequest instance. */
    constructor($$source: Partial<CreateEventRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateEventRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateEventRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateEventRequest($$parsedSource as Partial<CreateEventRequest>);
    }
}

export class CreatePlayerRequest {
    "tag": string;
    "team": string;
    "region": string;

    /** Creates a new CreatePlayerRequest instance. */
    constructor($$source: Partial<CreatePlayerRequest> = {}) {
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("team" in $$source)) {
            this["team"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatePlayerRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatePlayerRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreatePlayerRequest($$parsedSource as Partial<CreatePlayerRequest>);
    }
}

export class CreateSetRequest {
    "tournament_id": string;
    "player1_id": string;
    "player2_id": string;
    "round": string;
    "best_of": number;

    /** Creates a new CreateSetRequest instance. */
    constructor($$source: Partial<CreateSetRequest> = {}) {
        if (!("tournament_id" in $$source)) {
            this["tournament_id"] = "";
        }
        if (!("player1_id" in $$source)) {
            this["player1_id"] = "";
        }
        if (!("player2_id" in $$source)) {
            this["player2_id"] = "";
        }
        if (!("round" in $$source)) {
            this["round"] = "";
        }
        if (!("best_of" in $$source)) {
            this["best_of"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateSetRequest($$parsedSource as Partial<CreateSetRequest>);
    }
}

export class CreateTournamentRequest {
    "event_id": string;
    "name": string;
    "game": string;

    /** Creates a new CreateTournamentRequest instance. */
    constructor($$source: Partial<CreateTournamentRequest> = {}) {
        if (!("event_id" in $$source)) {
            this["event_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("game" in $$source)) {
            this["game"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTournamentRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTournamentRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateTournamentRequest($$parsedSource as Partial<CreateTournamentRequest>);
    }
}

export class MessageRequest {
    "type": string;
    "payload": any;

    /** Creates a new MessageRequest instance. */
    constructor($$source: Partial<MessageRequest> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageRequest($$parsedSource as Partial<MessageRequest>);
    }
}

export class PlayerStats {
    "player_id": string;
    "sets_played": number;
    "sets_won": number;
    "sets_lost": number;
    "win_rate": number;
    "games_won": number;
    "games_lost": number;

    /** Creates a new PlayerStats instance. */
    constructor($$source: Partial<PlayerStats> = {}) {
        if (!("player_id" in $$source)) {
            this["player_id"] = "";
        }
        if (!("sets_played" in $$source)) {
            this["sets_played"] = 0;
        }
        if (!("sets_won" in $$source)) {
            this["sets_won"] = 0;
        }
        if (!("sets_lost" in $$source)) {
            this["sets_lost"] = 0;
        }
        if (!("win_rate" in $$source)) {
            this["win_rate"] = 0;
        }
        if (!("games_won" in $$source)) {
            this["games_won"] = 0;
        }
        if (!("games_lost" in $$source)) {
            this["games_lost"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerStats instance from a string or object.
     */
    static createFrom($$source: any = {}): PlayerStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayerStats($$parsedSource as Partial<PlayerStats>);
    }
}

export class ReportSetRequest {
    "set_id": string;
    "winner_id": string;
    "player1_score": number;
    "player2_score": number;

    /** Creates a new ReportSetRequest instance. */
    constructor($$source: Partial<ReportSetRequest> = {}) {
        if (!("set_id" in $$source)) {
            this["set_id"] = "";
        }
        if (!("winner_id" in $$source)) {
            this["winner_id"] = "";
        }
        if (!("player1_score" in $$source)) {
            this["player1_score"] = 0;
        }
        if (!("player2_score" in $$source)) {
            this["player2_score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportSetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportSetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportSetRequest($$parsedSource as Partial<ReportSetRequest>);
    }
}

export class UpdateMatchRequest {
    "player1Name": string;
    "player1Team": string;
    "player1Score": number;
    "player1Character": string;
    "player2Name": string;
    "player2Team": string;
    "player2Score": number;
    "player2Character": string;
    "round": string;
    "bestOf": number;

    /** Creates a new UpdateMatchRequest instance. */
    constructor($$source: Partial<UpdateMatchRequest> = {}) {
        if (!("player1Name" in $$source)) {
            this["player1Name"] = "";
        }
        if (!("player1Team" in $$source)) {
            this["player1Team"] = "";
        }
        if (!("player1Score" in $$source)) {
            this["player1Score"] = 0;
        }
        if (!("player1Character" in $$source)) {
            this["player1Character"] = "";
        }
        if (!("player2Name" in $$source)) {
            this["player2Name"] = "";
        }
        if (!("player2Team" in $$source)) {
            this["player2Team"] = "";
        }
        if (!("player2Score" in $$source)) {
            this["player2Score"] = 0;
        }
        if (!("player2Character" in $$source)) {
            this["player2Character"] = "";
        }
        if (!("round" in $$source)) {
            this["round"] = "";
        }
        if (!("bestOf" in $$source)) {
            this["bestOf"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateMatchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateMatchRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateMatchRequest($$parsedSource as Partial<UpdateMatchRequest>);
    }
}

export class UpdateSetScoreRequest {
    "set_id": string;
    "player1_score": number;
    "player2_score": number;

    /** Creates a new UpdateSetScoreRequest instance. */
    constructor($$source: Partial<UpdateSetScoreRequest> = {}) {
        if (!("set_id" in $$source)) {
            this["set_id"] = "";
        }
        if (!("player1_score" in $$source)) {
            this["player1_score"] = 0;
        }
        if (!("player2_score" in $$source)) {
            this["player2_score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateSetScoreRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateSetScoreRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateSetScoreRequest($$parsedSource as Partial<UpdateSetScoreRequest>);
    }
}

export class UpdateTournamentRequest {
    "id": string;
    "name": string;
    "game": string;

    /** Creates a new UpdateTournamentRequest instance. */
    constructor($$source: Partial<UpdateTournamentRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("game" in $$source)) {
            this["game"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateTournamentRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateTournamentRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateTournamentRequest($$parsedSource as Partial<UpdateTournamentRequest>);
    }
}
