// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum Source {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceManual = "manual",
    SourceStartGG = "startgg",
    SourceChallonge = "challonge",
};

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusNew = "NEW",
    StatusActive = "ACTIVE",
    StatusCompleted = "COMPLETED",
    StatusDisabled = "DISABLED",
    StatusDeleted = "DELETED",
};
