// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as constant$0 from "../../constant/models.js";

export class Commentator {
    "id": string;
    "name": string;
    "handle": string;
    "pronouns": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Commentator instance. */
    constructor($$source: Partial<Commentator> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("handle" in $$source)) {
            this["handle"] = "";
        }
        if (!("pronouns" in $$source)) {
            this["pronouns"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Commentator instance from a string or object.
     */
    static createFrom($$source: any = {}): Commentator {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Commentator($$parsedSource as Partial<Commentator>);
    }
}

export class Event {
    "id": string;
    "name": string;
    "status": constant$0.Status;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Event instance. */
    constructor($$source: Partial<Event> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = constant$0.Status.$zero;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     */
    static createFrom($$source: any = {}): Event {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Event($$parsedSource as Partial<Event>);
    }
}

export class Player {
    "id": string;
    "tag": string;
    "team": string;
    "region": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Player instance. */
    constructor($$source: Partial<Player> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("team" in $$source)) {
            this["team"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Player instance from a string or object.
     */
    static createFrom($$source: any = {}): Player {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Player($$parsedSource as Partial<Player>);
    }
}

export class Set {
    "id": string;
    "tournament_id": string;
    "player1_id": string;
    "player2_id": string;
    "winner_id": string;
    "player1_score": number;
    "player2_score": number;
    "round": string;
    "best_of": number;
    "status": constant$0.Status;
    "external_id": string;
    "round_order": number;
    "player1"?: Player | null;
    "player2"?: Player | null;
    "winner"?: Player | null;
    "created_at": string;

    /** Creates a new Set instance. */
    constructor($$source: Partial<Set> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("tournament_id" in $$source)) {
            this["tournament_id"] = "";
        }
        if (!("player1_id" in $$source)) {
            this["player1_id"] = "";
        }
        if (!("player2_id" in $$source)) {
            this["player2_id"] = "";
        }
        if (!("winner_id" in $$source)) {
            this["winner_id"] = "";
        }
        if (!("player1_score" in $$source)) {
            this["player1_score"] = 0;
        }
        if (!("player2_score" in $$source)) {
            this["player2_score"] = 0;
        }
        if (!("round" in $$source)) {
            this["round"] = "";
        }
        if (!("best_of" in $$source)) {
            this["best_of"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = constant$0.Status.$zero;
        }
        if (!("external_id" in $$source)) {
            this["external_id"] = "";
        }
        if (!("round_order" in $$source)) {
            this["round_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Set instance from a string or object.
     */
    static createFrom($$source: any = {}): Set {
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType1;
        const $$createField14_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("player1" in $$parsedSource) {
            $$parsedSource["player1"] = $$createField12_0($$parsedSource["player1"]);
        }
        if ("player2" in $$parsedSource) {
            $$parsedSource["player2"] = $$createField13_0($$parsedSource["player2"]);
        }
        if ("winner" in $$parsedSource) {
            $$parsedSource["winner"] = $$createField14_0($$parsedSource["winner"]);
        }
        return new Set($$parsedSource as Partial<Set>);
    }
}

export class Tournament {
    "id": string;
    "event_id": string;
    "name": string;
    "game": string;
    "source": constant$0.Source;
    "external_id": string;
    "bracket_type": string;
    "status": constant$0.Status;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Tournament instance. */
    constructor($$source: Partial<Tournament> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("event_id" in $$source)) {
            this["event_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("game" in $$source)) {
            this["game"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = constant$0.Source.$zero;
        }
        if (!("external_id" in $$source)) {
            this["external_id"] = "";
        }
        if (!("bracket_type" in $$source)) {
            this["bracket_type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = constant$0.Status.$zero;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tournament instance from a string or object.
     */
    static createFrom($$source: any = {}): Tournament {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tournament($$parsedSource as Partial<Tournament>);
    }
}

// Private type creation functions
const $$createType0 = Player.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
