// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetGameManifest looks up the asset manifest for a game by name (case-insensitive).
 * Tries dir-name prefix matching first, then falls back to matching the manifest's
 * Name field — so full names like "Street Fighter 6" resolve to the "sf6" pack.
 * Returns a default manifest (1 character per player, no character list) if not found.
 */
export function GetGameManifest(game: string): $CancellablePromise<$models.GameManifest | null> {
    return $Call.ByID(2128583996, game).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListInstalledAssets returns a summary of every game asset pack in assetsDir.
 */
export function ListInstalledAssets(): $CancellablePromise<($models.InstalledAsset | null)[]> {
    return $Call.ByID(245410824).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.GameManifest.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.InstalledAsset.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
