// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../domain/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../dto/models.js";

export function CreateCommentator(req: dto$0.CreateCommentatorRequest): $CancellablePromise<model$0.Commentator | null> {
    return $Call.ByID(4134501569, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteCommentator(id: string): $CancellablePromise<void> {
    return $Call.ByID(2395062368, id);
}

export function GetAll(): $CancellablePromise<(model$0.Commentator | null)[]> {
    return $Call.ByID(2213676695).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Commentator.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
