// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CharacterInfo {
    "id": string;
    "name": string;

    /** Creates a new CharacterInfo instance. */
    constructor($$source: Partial<CharacterInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CharacterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CharacterInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CharacterInfo($$parsedSource as Partial<CharacterInfo>);
    }
}

export class GameManifest {
    "name": string;
    "characters_per_player": number;
    "characters": CharacterInfo[];

    /** Creates a new GameManifest instance. */
    constructor($$source: Partial<GameManifest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("characters_per_player" in $$source)) {
            this["characters_per_player"] = 0;
        }
        if (!("characters" in $$source)) {
            this["characters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameManifest instance from a string or object.
     */
    static createFrom($$source: any = {}): GameManifest {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("characters" in $$parsedSource) {
            $$parsedSource["characters"] = $$createField2_0($$parsedSource["characters"]);
        }
        return new GameManifest($$parsedSource as Partial<GameManifest>);
    }
}

/**
 * InstalledAsset summarises a game asset pack for display in the UI.
 */
export class InstalledAsset {
    "dir_name": string;
    "name": string;
    "characters_per_player": number;
    "character_count": number;

    /** Creates a new InstalledAsset instance. */
    constructor($$source: Partial<InstalledAsset> = {}) {
        if (!("dir_name" in $$source)) {
            this["dir_name"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("characters_per_player" in $$source)) {
            this["characters_per_player"] = 0;
        }
        if (!("character_count" in $$source)) {
            this["character_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledAsset instance from a string or object.
     */
    static createFrom($$source: any = {}): InstalledAsset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstalledAsset($$parsedSource as Partial<InstalledAsset>);
    }
}

export class OverlayField {
    "key": string;
    "label": string;
    "type": string;
    "options"?: string[];

    /** Creates a new OverlayField instance. */
    constructor($$source: Partial<OverlayField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverlayField instance from a string or object.
     */
    static createFrom($$source: any = {}): OverlayField {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new OverlayField($$parsedSource as Partial<OverlayField>);
    }
}

export class OverlayManifest {
    "name": string;
    "subscribes": string[];
    "fields": OverlayField[];

    /** Creates a new OverlayManifest instance. */
    constructor($$source: Partial<OverlayManifest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("subscribes" in $$source)) {
            this["subscribes"] = [];
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OverlayManifest instance from a string or object.
     */
    static createFrom($$source: any = {}): OverlayManifest {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subscribes" in $$parsedSource) {
            $$parsedSource["subscribes"] = $$createField1_0($$parsedSource["subscribes"]);
        }
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        return new OverlayManifest($$parsedSource as Partial<OverlayManifest>);
    }
}

export class PackInfo {
    "dir_name": string;
    "name": string;
    "author": string;
    "version": string;
    "description": string;
    "overlays": string[];

    /** Creates a new PackInfo instance. */
    constructor($$source: Partial<PackInfo> = {}) {
        if (!("dir_name" in $$source)) {
            this["dir_name"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("overlays" in $$source)) {
            this["overlays"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PackInfo {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("overlays" in $$parsedSource) {
            $$parsedSource["overlays"] = $$createField5_0($$parsedSource["overlays"]);
        }
        return new PackInfo($$parsedSource as Partial<PackInfo>);
    }
}

// Private type creation functions
const $$createType0 = CharacterInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = OverlayField.createFrom;
const $$createType4 = $Create.Array($$createType3);
