// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../domain/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../dto/models.js";

export function CreatePlayer(req: dto$0.CreatePlayerRequest): $CancellablePromise<model$0.Player | null> {
    return $Call.ByID(3550470039, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeletePlayer(id: string): $CancellablePromise<void> {
    return $Call.ByID(1195645600, id);
}

export function GetAll(): $CancellablePromise<(model$0.Player | null)[]> {
    return $Call.ByID(1086744917).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetAllStats(): $CancellablePromise<(dto$0.PlayerStats | null)[]> {
    return $Call.ByID(1059681596).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Player.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = dto$0.PlayerStats.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
