// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../dto/models.js";

export function Broadcast(data: dto$0.MessageRequest): $CancellablePromise<void> {
    return $Call.ByID(1117437011, data);
}

export function BroadcastMessage(msgType: string, payload: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(3277044218, msgType, payload);
}

export function ClientCount(): $CancellablePromise<number> {
    return $Call.ByID(2252045982);
}

/**
 * GetConfigPort returns the last-saved port from config (default 3000).
 * Used by Settings on mount so the field shows the persisted value even
 * before the server has started.
 */
export function GetConfigPort(): $CancellablePromise<number> {
    return $Call.ByID(623233885);
}

export function GetPort(): $CancellablePromise<number> {
    return $Call.ByID(1464434911);
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(495814815);
}

export function StartServer(port: number): $CancellablePromise<void> {
    return $Call.ByID(2561604311, port);
}

export function StopServer(): $CancellablePromise<void> {
    return $Call.ByID(2553937499);
}
