// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../domain/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../dto/models.js";

export function CreateSet(req: dto$0.CreateSetRequest): $CancellablePromise<model$0.Set | null> {
    return $Call.ByID(3754340915, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteSet(id: string): $CancellablePromise<void> {
    return $Call.ByID(3444410338, id);
}

export function GetByTournament(tournamentID: string): $CancellablePromise<(model$0.Set | null)[]> {
    return $Call.ByID(1853243605, tournamentID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ReportResult(req: dto$0.ReportSetRequest): $CancellablePromise<void> {
    return $Call.ByID(1396844858, req);
}

export function UpdateScore(req: dto$0.UpdateSetScoreRequest): $CancellablePromise<void> {
    return $Call.ByID(539356918, req);
}

// Private type creation functions
const $$createType0 = model$0.Set.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
