// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ImportTournament imports a start.gg tournament into Zhago.
 * url is a full start.gg URL (e.g. https://start.gg/tournament/the-fight-2026).
 * token is the user's start.gg API token from Developer Settings.
 */
export function ImportTournament(url: string, token: string): $CancellablePromise<void> {
    return $Call.ByID(3610095245, url, token);
}
