// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetActivePack(): $CancellablePromise<string> {
    return $Call.ByID(2520190972);
}

export function GetActiveTemplate(overlayType: string): $CancellablePromise<string> {
    return $Call.ByID(120753607, overlayType);
}

export function GetOverlayManifest(overlayType: string): $CancellablePromise<$models.OverlayManifest | null> {
    return $Call.ByID(3621418852, overlayType).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListPacks(): $CancellablePromise<($models.PackInfo | null)[]> {
    return $Call.ByID(2907734805).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetActivePack(dirName: string): $CancellablePromise<void> {
    return $Call.ByID(3123377632, dirName);
}

export function SetActiveTemplate(overlayType: string, packDirName: string): $CancellablePromise<void> {
    return $Call.ByID(3823493643, overlayType, packDirName);
}

// Private type creation functions
const $$createType0 = $models.OverlayManifest.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.PackInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
