// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../domain/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../dto/models.js";

export function ActivateTournament(id: string): $CancellablePromise<void> {
    return $Call.ByID(3566661118, id);
}

export function CreateTournament(req: dto$0.CreateTournamentRequest): $CancellablePromise<model$0.Tournament | null> {
    return $Call.ByID(633419415, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteTournament(id: string): $CancellablePromise<void> {
    return $Call.ByID(2691781800, id);
}

export function GetAll(): $CancellablePromise<(model$0.Tournament | null)[]> {
    return $Call.ByID(1282366695).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetByEvent(eventID: string): $CancellablePromise<(model$0.Tournament | null)[]> {
    return $Call.ByID(68727603, eventID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateTournament(req: dto$0.UpdateTournamentRequest): $CancellablePromise<void> {
    return $Call.ByID(2994105246, req);
}

// Private type creation functions
const $$createType0 = model$0.Tournament.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
