// Bun's --compile embeds only files reached via a static `import ... with { type: "file" }`.
// There is no glob or directory flag, so this script walks build/runtime asset
// directories and writes one static import per file.
import { readdir, mkdir, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';

const DIST_DIR = join(import.meta.dir, '..', 'app', 'dist');
const CORE_ASSETS_DIR = join(import.meta.dir, '..', 'assets');
const OUT_DIR = join(import.meta.dir, '..', '.gen');
const OUT_FILE = join(OUT_DIR, 'ui-assets.ts');

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(full)));
    else files.push(full);
  }
  return files;
}

function toUrlPath(root: string, file: string): string {
  return '/' + relative(root, file).split(sep).join('/');
}

function toImportPath(file: string): string {
  return './' + relative(OUT_DIR, file).split(sep).join('/');
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const uiFiles = await walk(DIST_DIR).catch(() => []);
  const coreAssetFiles = await walk(CORE_ASSETS_DIR).catch(() => []);

  const imports: string[] = [];
  const uiEntries: string[] = [];
  const coreAssetEntries: string[] = [];
  let i = 0;

  for (const file of uiFiles) {
    const varName = `f${i++}`;
    imports.push(
      `import ${varName} from ${JSON.stringify(toImportPath(file))} with { type: "file" };`,
    );
    uiEntries.push(`  ${JSON.stringify(toUrlPath(DIST_DIR, file))}: ${varName},`);
  }

  for (const file of coreAssetFiles) {
    const varName = `f${i++}`;
    imports.push(
      `import ${varName} from ${JSON.stringify(toImportPath(file))} with { type: "file" };`,
    );
    coreAssetEntries.push(`  ${JSON.stringify(toUrlPath(CORE_ASSETS_DIR, file))}: ${varName},`);
  }

  const contents = `// @ts-nocheck - auto-generated by scripts/generate-ui-embed.ts - do not edit by hand
//
// Plain tsc does not understand Bun's \`with { type: "file" }\` import semantics.
// Bun's bundler and runtime handle these correctly, which is what matters for
// the compiled binary.
${imports.join('\n')}

export const uiAssets: Record<string, string> = {
${uiEntries.join('\n')}
};

export const coreAssets: Record<string, string> = {
${coreAssetEntries.join('\n')}
};
`;

  await writeFile(OUT_FILE, contents);
  console.log(
    `[generate-ui-embed] embedded ${uiFiles.length} app file(s), ${coreAssetFiles.length} core asset file(s)`,
  );
}

await main();
