// Bun's --compile embeds only files reached via a static `import ... with { type: "file" }`
// — there's no glob or directory flag (confirmed against the installed Bun version's own
// CLI --help and bun.d.ts, not assumed). Vite's dist/ has hashed, build-generated filenames,
// so this script walks it and writes one static import per file, keyed by URL path, mirroring
// Abyss's `//go:embed dist/*` but doing by hand what Go's embed does natively.
import { readdir, mkdir, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';

const DIST_DIR = join(import.meta.dir, '..', 'app', 'dist');
const OUT_DIR = join(import.meta.dir, '..', '.gen');
const OUT_FILE = join(OUT_DIR, 'ui-assets.ts');

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(full)));
    else files.push(full);
  }
  return files;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  // Bun.file(...).exists() checks *file* existence, not directory existence — it
  // reports false for a real directory path, which silently produced an empty
  // map even with ui/dist present. readdir() is the correct existence check here.
  const files = await walk(DIST_DIR).catch(() => []);

  if (files.length === 0) {
    // No build yet (dev mode never needs this — Vite serves the UI directly).
    await writeFile(
      OUT_FILE,
      `// @ts-nocheck — auto-generated by scripts/generate-ui-embed.ts — no app/dist found\nexport const uiAssets: Record<string, string> = {}\n`,
    );
    console.log('[generate-ui-embed] app/dist not found — wrote empty map');
    return;
  }

  const imports: string[] = [];
  const entries: string[] = [];
  files.forEach((file, i) => {
    const urlPath = '/' + relative(DIST_DIR, file).split(sep).join('/');
    const varName = `f${i}`;
    const importPath = relative(OUT_DIR, file).split(sep).join('/');
    imports.push(
      `import ${varName} from ${JSON.stringify('./' + importPath)} with { type: "file" };`,
    );
    entries.push(`  ${JSON.stringify(urlPath)}: ${varName},`);
  });

  const contents = `// @ts-nocheck — auto-generated by scripts/generate-ui-embed.ts — do not edit by hand
//
// Plain tsc doesn't understand Bun's \`with { type: "file" }\` import semantics
// (unknown extensions, and .html resolves to Bun's special HTMLBundle type
// instead of a string) — Bun's own bundler and runtime handle these correctly,
// which is what actually matters, since this file is never hand-edited.
${imports.join('\n')}

export const uiAssets: Record<string, string> = {
${entries.join('\n')}
};
`;
  await writeFile(OUT_FILE, contents);
  console.log(`[generate-ui-embed] embedded ${files.length} file(s) from app/dist`);
}

await main();
