// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sse} from '../models';

export function IsServerRunning():Promise<boolean>;

export function Save(arg1:sse.MatchDataUpdateDTO):Promise<void>;

export function StartHTTPServer(arg1:string):Promise<void>;

export function StopHTTPServer():Promise<void>;
