// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}

export function StartHTTPServer(arg1) {
  return window['go']['main']['App']['StartHTTPServer'](arg1);
}

export function StopHTTPServer() {
  return window['go']['main']['App']['StopHTTPServer']();
}
